/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AaveReservesData {
    #[serde(rename = "current_atoken_balance")]
    pub current_atoken_balance: String,
    #[serde(rename = "current_borrow_balance")]
    pub current_borrow_balance: String,
    #[serde(rename = "principal_borrow_balance")]
    pub principal_borrow_balance: String,
    #[serde(rename = "borrow_rate_mode")]
    pub borrow_rate_mode: String,
    #[serde(rename = "borrow_rate")]
    pub borrow_rate: String,
    #[serde(rename = "liquidity_rate")]
    pub liquidity_rate: String,
    #[serde(rename = "origination_fee")]
    pub origination_fee: String,
    #[serde(rename = "variable_borrow_index")]
    pub variable_borrow_index: String,
    #[serde(rename = "last_update_timestamp")]
    pub last_update_timestamp: String,
    #[serde(rename = "usage_as_collateral_enabled")]
    pub usage_as_collateral_enabled: String,
}

impl AaveReservesData {
    pub fn new(current_atoken_balance: String, current_borrow_balance: String, principal_borrow_balance: String, borrow_rate_mode: String, borrow_rate: String, liquidity_rate: String, origination_fee: String, variable_borrow_index: String, last_update_timestamp: String, usage_as_collateral_enabled: String) -> AaveReservesData {
        AaveReservesData {
            current_atoken_balance,
            current_borrow_balance,
            principal_borrow_balance,
            borrow_rate_mode,
            borrow_rate,
            liquidity_rate,
            origination_fee,
            variable_borrow_index,
            last_update_timestamp,
            usage_as_collateral_enabled,
        }
    }
}


