/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbiEncodeInput {
    #[serde(rename = "abi", deserialize_with = "Option::deserialize")]
    pub abi: Option<serde_json::Value>,
    #[serde(rename = "functionName")]
    pub function_name: String,
    #[serde(rename = "params")]
    pub params: Vec<serde_json::Value>,
}

impl AbiEncodeInput {
    pub fn new(abi: Option<serde_json::Value>, function_name: String, params: Vec<serde_json::Value>) -> AbiEncodeInput {
        AbiEncodeInput {
            abi,
            function_name,
            params,
        }
    }
}


