/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Block {
    #[serde(rename = "number")]
    pub number: String,
    #[serde(rename = "hash")]
    pub hash: String,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
}

impl Block {
    pub fn new(number: String, hash: String, timestamp: String) -> Block {
        Block {
            number,
            hash,
            timestamp,
        }
    }
}


