/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Bridge {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "logoURI")]
    pub logo_uri: String,
    #[serde(rename = "supportedChains")]
    pub supported_chains: Vec<crate::models::BridgeSupportedChain>,
}

impl Bridge {
    pub fn new(key: String, name: String, logo_uri: String, supported_chains: Vec<crate::models::BridgeSupportedChain>) -> Bridge {
        Bridge {
            key,
            name,
            logo_uri,
            supported_chains,
        }
    }
}


