/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BundleTransactionsInput {
    #[serde(rename = "rpcUrl")]
    pub rpc_url: String,
    #[serde(rename = "transactionIds")]
    pub transaction_ids: Vec<String>,
}

impl BundleTransactionsInput {
    pub fn new(rpc_url: String, transaction_ids: Vec<String>) -> BundleTransactionsInput {
        BundleTransactionsInput {
            rpc_url,
            transaction_ids,
        }
    }
}


