/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChainNativeToken {
    #[serde(rename = "priceUSD")]
    pub price_usd: String,
    #[serde(rename = "logoURI")]
    pub logo_uri: String,
    #[serde(rename = "coinKey")]
    pub coin_key: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "decimals")]
    pub decimals: f64,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "chainId")]
    pub chain_id: f64,
    #[serde(rename = "address")]
    pub address: String,
}

impl ChainNativeToken {
    pub fn new(price_usd: String, logo_uri: String, coin_key: String, name: String, decimals: f64, symbol: String, chain_id: f64, address: String) -> ChainNativeToken {
        ChainNativeToken {
            price_usd,
            logo_uri,
            coin_key,
            name,
            decimals,
            symbol,
            chain_id,
            address,
        }
    }
}


