/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChainsResponse {
    #[serde(rename = "chains")]
    pub chains: Vec<crate::models::Chain>,
}

impl ChainsResponse {
    pub fn new(chains: Vec<crate::models::Chain>) -> ChainsResponse {
        ChainsResponse {
            chains,
        }
    }
}


