/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectionsResponse {
    #[serde(rename = "connections")]
    pub connections: Vec<crate::models::Connection>,
}

impl ConnectionsResponse {
    pub fn new(connections: Vec<crate::models::Connection>) -> ConnectionsResponse {
        ConnectionsResponse {
            connections,
        }
    }
}


