/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CryptoCurrency {
    #[serde(rename = "networkDisplayName")]
    pub network_display_name: String,
    #[serde(rename = "icon")]
    pub icon: String,
    #[serde(rename = "chainId")]
    pub chain_id: f64,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "decimals")]
    pub decimals: f64,
    #[serde(rename = "network")]
    pub network: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "id")]
    pub id: String,
}

impl CryptoCurrency {
    pub fn new(network_display_name: String, icon: String, chain_id: f64, address: String, decimals: f64, network: String, symbol: String, name: String, code: String, id: String) -> CryptoCurrency {
        CryptoCurrency {
            network_display_name,
            icon,
            chain_id,
            address,
            decimals,
            network,
            symbol,
            name,
            code,
            id,
        }
    }
}


