/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeployInput {
    #[serde(rename = "chain_id", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<String>,
    #[serde(rename = "abi")]
    pub abi: String,
    #[serde(rename = "bytecode")]
    pub bytecode: String,
    #[serde(rename = "constructor_args", skip_serializing_if = "Option::is_none")]
    pub constructor_args: Option<String>,
}

impl DeployInput {
    pub fn new(abi: String, bytecode: String) -> DeployInput {
        DeployInput {
            chain_id: None,
            abi,
            bytecode,
            constructor_args: None,
        }
    }
}


