/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EnsResolveInput {
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "chain_id")]
    pub chain_id: String,
}

impl EnsResolveInput {
    pub fn new(domain: String, chain_id: String) -> EnsResolveInput {
        EnsResolveInput {
            domain,
            chain_id,
        }
    }
}


