/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeCost {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "percentage")]
    pub percentage: f64,
    #[serde(rename = "token")]
    pub token: Box<crate::models::Token>,
    #[serde(rename = "amount")]
    pub amount: f64,
}

impl FeeCost {
    pub fn new(name: String, percentage: f64, token: crate::models::Token, amount: f64) -> FeeCost {
        FeeCost {
            name,
            percentage,
            token: Box::new(token),
            amount,
        }
    }
}


