/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GasPrice {
    #[serde(rename = "lastTimestamp")]
    pub last_timestamp: f64,
    #[serde(rename = "chainId")]
    pub chain_id: String,
    #[serde(rename = "unitName")]
    pub unit_name: String,
    #[serde(rename = "history")]
    pub history: Vec<crate::models::GasPriceHistoryInner>,
    #[serde(rename = "average24h")]
    pub average24h: f64,
    #[serde(rename = "average7d")]
    pub average7d: f64,
}

impl GasPrice {
    pub fn new(last_timestamp: f64, chain_id: String, unit_name: String, history: Vec<crate::models::GasPriceHistoryInner>, average24h: f64, average7d: f64) -> GasPrice {
        GasPrice {
            last_timestamp,
            chain_id,
            unit_name,
            history,
            average24h,
            average7d,
        }
    }
}


