/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GasCost {
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "estimate")]
    pub estimate: String,
    #[serde(rename = "limit")]
    pub limit: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "amountUSD")]
    pub amount_usd: String,
    #[serde(rename = "token")]
    pub token: Box<crate::models::TokenInfo>,
}

impl GasCost {
    pub fn new(r#type: String, price: String, estimate: String, limit: String, amount: String, amount_usd: String, token: crate::models::TokenInfo) -> GasCost {
        GasCost {
            r#type,
            price,
            estimate,
            limit,
            amount,
            amount_usd,
            token: Box::new(token),
        }
    }
}


