/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSupportedOnRampsResponseMessageInnerIcons {
    #[serde(rename = "png")]
    pub png: Box<crate::models::GetSupportedOnRampsResponseMessageInnerIconsPng>,
    #[serde(rename = "svg")]
    pub svg: String,
}

impl GetSupportedOnRampsResponseMessageInnerIcons {
    pub fn new(png: crate::models::GetSupportedOnRampsResponseMessageInnerIconsPng, svg: String) -> GetSupportedOnRampsResponseMessageInnerIcons {
        GetSupportedOnRampsResponseMessageInnerIcons {
            png: Box::new(png),
            svg,
        }
    }
}


