/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSwapDto {
    #[serde(rename = "src")]
    pub src: String,
    #[serde(rename = "dst")]
    pub dst: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "slippage")]
    pub slippage: f64,
    #[serde(rename = "protocols", skip_serializing_if = "Option::is_none")]
    pub protocols: Option<String>,
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<String>,
    #[serde(rename = "disableEstimate", skip_serializing_if = "Option::is_none")]
    pub disable_estimate: Option<bool>,
    #[serde(rename = "permit", skip_serializing_if = "Option::is_none")]
    pub permit: Option<String>,
    #[serde(rename = "includeTokensInfo", skip_serializing_if = "Option::is_none")]
    pub include_tokens_info: Option<bool>,
    #[serde(rename = "includeProtocols", skip_serializing_if = "Option::is_none")]
    pub include_protocols: Option<bool>,
    #[serde(rename = "compatibility", skip_serializing_if = "Option::is_none")]
    pub compatibility: Option<bool>,
    #[serde(rename = "allowPartialFill", skip_serializing_if = "Option::is_none")]
    pub allow_partial_fill: Option<bool>,
    #[serde(rename = "parts", skip_serializing_if = "Option::is_none")]
    pub parts: Option<String>,
    #[serde(rename = "mainRouteParts", skip_serializing_if = "Option::is_none")]
    pub main_route_parts: Option<String>,
    #[serde(rename = "connectorTokens", skip_serializing_if = "Option::is_none")]
    pub connector_tokens: Option<String>,
    #[serde(rename = "complexityLevel", skip_serializing_if = "Option::is_none")]
    pub complexity_level: Option<String>,
    #[serde(rename = "gasLimit", skip_serializing_if = "Option::is_none")]
    pub gas_limit: Option<String>,
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
    #[serde(rename = "referrer", skip_serializing_if = "Option::is_none")]
    pub referrer: Option<String>,
    #[serde(rename = "receiver", skip_serializing_if = "Option::is_none")]
    pub receiver: Option<String>,
    #[serde(rename = "chainId", skip_serializing_if = "Option::is_none")]
    pub chain_id: Option<f64>,
}

impl GetSwapDto {
    pub fn new(src: String, dst: String, amount: String, from: String, slippage: f64) -> GetSwapDto {
        GetSwapDto {
            src,
            dst,
            amount,
            from,
            slippage,
            protocols: None,
            fee: None,
            disable_estimate: None,
            permit: None,
            include_tokens_info: None,
            include_protocols: None,
            compatibility: None,
            allow_partial_fill: None,
            parts: None,
            main_route_parts: None,
            connector_tokens: None,
            complexity_level: None,
            gas_limit: None,
            gas_price: None,
            referrer: None,
            receiver: None,
            chain_id: None,
        }
    }
}


