/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSupportedOnRampsResponseMessageInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "icons")]
    pub icons: Box<crate::models::GetSupportedOnRampsResponseMessageInnerIcons>,
    #[serde(rename = "icon")]
    pub icon: String,
}

impl GetSupportedOnRampsResponseMessageInner {
    pub fn new(id: String, display_name: String, icons: crate::models::GetSupportedOnRampsResponseMessageInnerIcons, icon: String) -> GetSupportedOnRampsResponseMessageInner {
        GetSupportedOnRampsResponseMessageInner {
            id,
            display_name,
            icons: Box::new(icons),
            icon,
        }
    }
}


