/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IbcTransferTransactionInput {
    #[serde(rename = "from_address")]
    pub from_address: String,
    #[serde(rename = "to_address")]
    pub to_address: String,
    #[serde(rename = "demon")]
    pub demon: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "chain_id")]
    pub chain_id: String,
    #[serde(rename = "sequence")]
    pub sequence: f64,
    #[serde(rename = "account_number")]
    pub account_number: f64,
    #[serde(rename = "fee_demon")]
    pub fee_demon: String,
    #[serde(rename = "fee_amount")]
    pub fee_amount: String,
    #[serde(rename = "gas_limit")]
    pub gas_limit: f64,
    #[serde(rename = "memo")]
    pub memo: String,
    #[serde(rename = "timeout_height")]
    pub timeout_height: f64,
    #[serde(rename = "source_port")]
    pub source_port: String,
    #[serde(rename = "source_channel")]
    pub source_channel: String,
}

impl IbcTransferTransactionInput {
    pub fn new(from_address: String, to_address: String, demon: String, amount: String, chain_id: String, sequence: f64, account_number: f64, fee_demon: String, fee_amount: String, gas_limit: f64, memo: String, timeout_height: f64, source_port: String, source_channel: String) -> IbcTransferTransactionInput {
        IbcTransferTransactionInput {
            from_address,
            to_address,
            demon,
            amount,
            chain_id,
            sequence,
            account_number,
            fee_demon,
            fee_amount,
            gas_limit,
            memo,
            timeout_height,
            source_port,
            source_channel,
        }
    }
}


