/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InftTransfer {
    #[serde(rename = "transactionHash")]
    pub transaction_hash: String,
    #[serde(rename = "contract")]
    pub contract: String,
    #[serde(rename = "logIndex")]
    pub log_index: String,
    #[serde(rename = "tokenContractType")]
    pub token_contract_type: String,
    #[serde(rename = "tokenName")]
    pub token_name: String,
    #[serde(rename = "tokenSymbol")]
    pub token_symbol: String,
    #[serde(rename = "triggers", skip_serializing_if = "Option::is_none")]
    pub triggers: Option<Vec<crate::models::TriggerOutput>>,
    #[serde(rename = "operator", deserialize_with = "Option::deserialize")]
    pub operator: Option<String>,
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "to")]
    pub to: String,
    #[serde(rename = "tokenId")]
    pub token_id: String,
    #[serde(rename = "amount")]
    pub amount: String,
}

impl InftTransfer {
    pub fn new(transaction_hash: String, contract: String, log_index: String, token_contract_type: String, token_name: String, token_symbol: String, operator: Option<String>, from: String, to: String, token_id: String, amount: String) -> InftTransfer {
        InftTransfer {
            transaction_hash,
            contract,
            log_index,
            token_contract_type,
            token_name,
            token_symbol,
            triggers: None,
            operator,
            from,
            to,
            token_id,
            amount,
        }
    }
}


