/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InftApprovalErc1155 {
    #[serde(rename = "transactionHash")]
    pub transaction_hash: String,
    #[serde(rename = "contract")]
    pub contract: String,
    #[serde(rename = "logIndex")]
    pub log_index: String,
    #[serde(rename = "account")]
    pub account: String,
    #[serde(rename = "operator")]
    pub operator: String,
    #[serde(rename = "approved")]
    pub approved: bool,
    #[serde(rename = "tokenContractType")]
    pub token_contract_type: String,
    #[serde(rename = "tokenName")]
    pub token_name: String,
    #[serde(rename = "tokenSymbol")]
    pub token_symbol: String,
}

impl InftApprovalErc1155 {
    pub fn new(transaction_hash: String, contract: String, log_index: String, account: String, operator: String, approved: bool, token_contract_type: String, token_name: String, token_symbol: String) -> InftApprovalErc1155 {
        InftApprovalErc1155 {
            transaction_hash,
            contract,
            log_index,
            account,
            operator,
            approved,
            token_contract_type,
            token_name,
            token_symbol,
        }
    }
}


