/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InftApprovalErc721 {
    #[serde(rename = "transactionHash")]
    pub transaction_hash: String,
    #[serde(rename = "contract")]
    pub contract: String,
    #[serde(rename = "logIndex")]
    pub log_index: String,
    #[serde(rename = "owner")]
    pub owner: String,
    #[serde(rename = "approved")]
    pub approved: String,
    #[serde(rename = "tokenId")]
    pub token_id: String,
    #[serde(rename = "tokenContractType")]
    pub token_contract_type: String,
    #[serde(rename = "tokenName")]
    pub token_name: String,
    #[serde(rename = "tokenSymbol")]
    pub token_symbol: String,
}

impl InftApprovalErc721 {
    pub fn new(transaction_hash: String, contract: String, log_index: String, owner: String, approved: String, token_id: String, token_contract_type: String, token_name: String, token_symbol: String) -> InftApprovalErc721 {
        InftApprovalErc721 {
            transaction_hash,
            contract,
            log_index,
            owner,
            approved,
            token_id,
            token_contract_type,
            token_name,
            token_symbol,
        }
    }
}


