/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LeveragerApiResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<Box<crate::models::InputBody>>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<serde_json::Value>>,
    #[serde(rename = "transaction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub transaction: Option<Option<serde_json::Value>>,
    #[serde(rename = "function", skip_serializing_if = "Option::is_none")]
    pub function: Option<String>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Vec<serde_json::Value>>,
    #[serde(rename = "user_op", skip_serializing_if = "Option::is_none")]
    pub user_op: Option<String>,
    #[serde(rename = "broadcasted", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub broadcasted: Option<Option<serde_json::Value>>,
}

impl LeveragerApiResponse {
    pub fn new(success: bool, message: String) -> LeveragerApiResponse {
        LeveragerApiResponse {
            success,
            message,
            body: None,
            address: None,
            data: None,
            transaction: None,
            function: None,
            params: None,
            user_op: None,
            broadcasted: None,
        }
    }
}


