/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    #[serde(rename = "fiat")]
    pub fiat: Vec<crate::models::FiatCurrency>,
    #[serde(rename = "crypto")]
    pub crypto: Vec<crate::models::CryptoCurrency>,
}

impl Message {
    pub fn new(fiat: Vec<crate::models::FiatCurrency>, crypto: Vec<crate::models::CryptoCurrency>) -> Message {
        Message {
            fiat,
            crypto,
        }
    }
}


