/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NonceResponse {
    #[serde(rename = "nonce")]
    pub nonce: f64,
}

impl NonceResponse {
    pub fn new(nonce: f64) -> NonceResponse {
        NonceResponse {
            nonce,
        }
    }
}


