/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PathVizImageConfig {
    #[serde(rename = "linkColors", skip_serializing_if = "Option::is_none")]
    pub link_colors: Option<Vec<String>>,
    #[serde(rename = "nodeColor", skip_serializing_if = "Option::is_none")]
    pub node_color: Option<String>,
    #[serde(rename = "nodeTextColor", skip_serializing_if = "Option::is_none")]
    pub node_text_color: Option<String>,
    #[serde(rename = "legendTextColor", skip_serializing_if = "Option::is_none")]
    pub legend_text_color: Option<String>,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
}

impl PathVizImageConfig {
    pub fn new() -> PathVizImageConfig {
        PathVizImageConfig {
            link_colors: None,
            node_color: None,
            node_text_color: None,
            legend_text_color: None,
            width: None,
            height: None,
        }
    }
}


