/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignMessage {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "data")]
    pub data: String,
    #[serde(rename = "encoding", skip_serializing_if = "Option::is_none")]
    pub encoding: Option<String>,
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<bool>,
    #[serde(rename = "signtype", skip_serializing_if = "Option::is_none")]
    pub signtype: Option<bool>,
}

impl SignMessage {
    pub fn new(data: String) -> SignMessage {
        SignMessage {
            name: None,
            data,
            encoding: None,
            header: None,
            signtype: None,
        }
    }
}


