/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Step {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "tool")]
    pub tool: String,
    #[serde(rename = "action")]
    pub action: Box<crate::models::Action>,
    #[serde(rename = "estimate")]
    pub estimate: Box<crate::models::Estimate>,
}

impl Step {
    pub fn new(id: String, r#type: String, tool: String, action: crate::models::Action, estimate: crate::models::Estimate) -> Step {
        Step {
            id,
            r#type,
            tool,
            action: Box::new(action),
            estimate: Box::new(estimate),
        }
    }
}


