/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupportedCurrenciesResponse {
    #[serde(rename = "message")]
    pub message: Box<crate::models::Message>,
}

impl SupportedCurrenciesResponse {
    pub fn new(message: crate::models::Message) -> SupportedCurrenciesResponse {
        SupportedCurrenciesResponse {
            message: Box::new(message),
        }
    }
}


