/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupportedDefaultResponseDefaultsId {
    #[serde(rename = "provider")]
    pub provider: String,
    #[serde(rename = "paymentMethod")]
    pub payment_method: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "source")]
    pub source: String,
}

impl SupportedDefaultResponseDefaultsId {
    pub fn new(provider: String, payment_method: String, amount: f64, target: String, source: String) -> SupportedDefaultResponseDefaultsId {
        SupportedDefaultResponseDefaultsId {
            provider,
            payment_method,
            amount,
            target,
            source,
        }
    }
}


