/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenDetails {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "chainId")]
    pub chain_id: f64,
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "decimals")]
    pub decimals: f64,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "coinKey")]
    pub coin_key: String,
    #[serde(rename = "logoURI")]
    pub logo_uri: String,
    #[serde(rename = "priceUSD")]
    pub price_usd: String,
}

impl TokenDetails {
    pub fn new(address: String, chain_id: f64, symbol: String, decimals: f64, name: String, coin_key: String, logo_uri: String, price_usd: String) -> TokenDetails {
        TokenDetails {
            address,
            chain_id,
            symbol,
            decimals,
            name,
            coin_key,
            logo_uri,
            price_usd,
        }
    }
}


