/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TokenAmount {
    #[serde(rename = "tokenAddress")]
    pub token_address: String,
    #[serde(rename = "amount")]
    pub amount: String,
}

impl TokenAmount {
    pub fn new(token_address: String, amount: String) -> TokenAmount {
        TokenAmount {
            token_address,
            amount,
        }
    }
}


