/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionInputSupportedParamsPartnerDataRedirectUrl {
    #[serde(rename = "success")]
    pub success: String,
}

impl TransactionInputSupportedParamsPartnerDataRedirectUrl {
    pub fn new(success: String) -> TransactionInputSupportedParamsPartnerDataRedirectUrl {
        TransactionInputSupportedParamsPartnerDataRedirectUrl {
            success,
        }
    }
}


