/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionInputSupportedParamsTheme {
    #[serde(rename = "borderRadius", deserialize_with = "Option::deserialize")]
    pub border_radius: Option<f64>,
    #[serde(rename = "cardColor")]
    pub card_color: String,
    #[serde(rename = "secondaryTextColor")]
    pub secondary_text_color: String,
    #[serde(rename = "primaryTextColor")]
    pub primary_text_color: String,
    #[serde(rename = "secondaryColor")]
    pub secondary_color: String,
    #[serde(rename = "primaryColor")]
    pub primary_color: String,
    #[serde(rename = "themeName")]
    pub theme_name: String,
    #[serde(rename = "isDark")]
    pub is_dark: bool,
}

impl TransactionInputSupportedParamsTheme {
    pub fn new(border_radius: Option<f64>, card_color: String, secondary_text_color: String, primary_text_color: String, secondary_color: String, primary_color: String, theme_name: String, is_dark: bool) -> TransactionInputSupportedParamsTheme {
        TransactionInputSupportedParamsTheme {
            border_radius,
            card_color,
            secondary_text_color,
            primary_text_color,
            secondary_color,
            primary_color,
            theme_name,
            is_dark,
        }
    }
}


