/*
 * moon-vault-api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionStatus {
    #[serde(rename = "chainId")]
    pub chain_id: f64,
    #[serde(rename = "txHash")]
    pub tx_hash: String,
    #[serde(rename = "txLink")]
    pub tx_link: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "token")]
    pub token: Box<crate::models::TokenInfo>,
    #[serde(rename = "gasPrice")]
    pub gas_price: String,
    #[serde(rename = "gasUsed")]
    pub gas_used: String,
}

impl TransactionStatus {
    pub fn new(chain_id: f64, tx_hash: String, tx_link: String, amount: String, token: crate::models::TokenInfo, gas_price: String, gas_used: String) -> TransactionStatus {
        TransactionStatus {
            chain_id,
            tx_hash,
            tx_link,
            amount,
            token: Box::new(token),
            gas_price,
            gas_used,
        }
    }
}


